### ISSUE TITLE
Can not run docker

### ISSUE THREAD

**Issue by pe1mew** [JCQ81/meshedapp#1]
Running the docker container seems to fail. 

When running `docker run --name meshedapp -e MESHTASTIC_HOST=192.168.20.232 -p 6374:6374 -v ~/meshedapp/data:/opt/meshedapp/store meshedapp` I am confronted with these messages: 
```
$ docker run --name meshedapp -e MESHTASTIC_HOST=192.168.20.232 -p 6374:6374 -v ~/meshedapp/data:/opt/meshedapp/store meshedapp
Traceback (most recent call last):
  File "/opt/meshedapp/./meshedapp.py", line 104, in <module>
    init()
  File "/opt/meshedapp/./meshedapp.py", line 23, in init
    interface = meshtastic.tcp_interface.TCPInterface(hostname=sys.argv[1])
  File "/usr/local/lib/python3.9/site-packages/meshtastic/tcp_interface.py", line 36, in __init__
    sock = socket.create_connection(server_address)
  File "/usr/lib64/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/lib64/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
Please note that 92.168.20.232 is the local server address. 
The server is running Ubuntu 20 64 bits. On the server port 6374 is free.

**Comment by pe1mew** [comment]
False alarm, wrong interpretation of environment variable.
